### PR TITLE
Fixes related to postgres host support

### PR DESCRIPTION
**Pull request by tvon**
Real change is in d25e5f674f110502894457f5548e6d23f1b76795, the rest is whitespace noise.

`IFS` was coming into the `db_exists` function with the value `/` which was fouling up the parsing and giving the error `psql: could not translate host name " postgres" to address: Name or service not known` (connecting to a docker container named `postgres`).  Main culprit was https://github.com/covermymeds/dbdeployer/commit/d25e5f674f110502894457f5548e6d23f1b76795#diff-1da8e68a5ee79d65cbc7360f59701a23L278 but the other changes seem sensible.

### CODE REVIEW

**Comment by tvon** [comment]
This supersedes #52

**Comment by cjestel** [comment]
These changes have been tested and look good. As mentioned the contents of 52 are included in this. I'll leave the docker dev/management of that file to you guys as you are more familiar with what it is accomplishing. I think there is an issue preventing remote deploy for postgres from working correclty, but I'll be working on that issue over the next couple of days.

**Comment by cjestel** [comment]
If you need me to cut a new release with this change, let me know. Otherwise I'll probably bundle this with some other changes I'm working on for the next published release.

**Comment by tvon** [comment]
Do not need a release, thanks.

FWIW I did run into another postgres issue, need the `dbtype/postgres/set_password_flags.sh` with:

```
function set_password_flags() {
  export PGPASSWORD=${password}
  return 0
}
```

**Comment by cjestel** [comment]
Yep, I didn't think we'd built out any of the postgres remote deploy features. That's actually what I'm working on currently to support deployments to Azure. I literally just created this file :-) in my branch.

**Pull request merged**
